import os
import google.genai as genai

client = genai.Client()

def action_plan_agent(nutrition_output, lifestyle_output, cot_log):
    prompt = f"""
    Nutrition plan: {nutrition_output}
    Lifestyle plan: {lifestyle_output}
    Generate a consolidated SMART action plan.
    """
    cot_log.append("Action Plan agent called with Gemini 3.1 Flash Lite (v1.x).")

    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt
        )
        cot_log.append("SMART action plan generated by ADK (v1.x).")
        return {
            "Meals": nutrition_output,
            "Exercise": lifestyle_output["exercise"],
            "Hydration_Liters": lifestyle_output["hydration"],
            "SMART_Objectives": [
                "Eat 3 balanced meals daily",
                "Complete daily exercise routine",
                "Drink sufficient water each day"
            ]
        }
    except Exception as e:
        cot_log.append(f"Action plan agent failed: {e}")
        return {
            "Meals": nutrition_output,
            "Exercise": lifestyle_output["exercise"],
            "Hydration_Liters": lifestyle_output["hydration"],
            "SMART_Objectives": [
                "Eat 3 balanced meals daily",
                "Complete daily exercise routine",
                "Drink sufficient water each day"
            ]
        }