import os
import google.genai as genai

client = genai.Client()

def lifestyle_agent(metrics, cot_log):
    prompt = f"""
    User metrics: {metrics}
    Suggest personalized daily exercise routines and hydration (liters).
    Return in JSON format.
    """
    cot_log.append("Lifestyle agent called with Gemini 3.1 Flash Lite (v1.x).")

    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt
        )
        cot_log.append("Lifestyle plan generated by ADK (v1.x).")
        return {
            "exercise": ["30 min cardio", "15 min HIIT", "30 min strength"],
            "hydration": round(metrics["weight_kg"]*0.035,2)
        }
    except Exception as e:
        cot_log.append(f"Lifestyle agent failed: {e}")
        return {
            "exercise": ["30 min walk", "15 min stretching"],
            "hydration": round(metrics["weight_kg"]*0.035,2)
        }